dist: xenial
services:
  - xvfb
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - 2.7.5
  - 3.0.4
  - 3.1.2
gemfile:
  - gemfiles/6.1.gemfile
  - gemfiles/7.0.gemfile
before_install:
  - nvm install 16
  - gem update --system
  - gem update bundler
before_script:
  - wget http://chromedriver.storage.googleapis.com/99.0.4844.51/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo rm chromedriver_linux64.zip
  - sudo apt-get install libnss3
  - sudo apt-get --only-upgrade install google-chrome-stable
  - sudo mv chromedriver /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/chromedriver
  - export DISPLAY=:99.0
  - sleep 3
script:
  - bundle exec rake db:migrate
  - bundle exec rake test
  - SKIP_COV=true bundle exec rake test:system
  - bundle exec rubocop
