dist: jammy
addons:
  chrome: stable
services:
  - xvfb
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - 3.1.4
  - 3.2.3
gemfile:
  - gemfiles/7.1.gemfile
before_install:
  - nvm install 18
  - gem update --system
  - gem update bundler
script:
  - bundle exec rake db:migrate
  - bundle exec rake test
  - SKIP_COV=true bundle exec rake test:system
  - bundle exec rubocop
